import time
import os

def eerstevraag():
    Answer = input("Wil je dit verhaaltje lezen? Ja/Nee: ")
    print("")
    if Answer == "Ja":
        time.sleep(1)
        print("goed laten we verder gaan!")
        print("")
        time.sleep(1)
        vragen()
    elif Answer == "Nee" :
        print("")
        print ("oke toch bedankt!")
        print("")
        time.sleep(1)
        exit() 
    else:
        print("vul een geldig antwoord in")
        print("")
        time.sleep(1)
        eerstevraag()
        

def start():
    print("Hello You, ik ben Jari")
    time.sleep(1)
    print("")
    print("Wie ben jij?")
    time.sleep(1)
    print("")
    Naam = input("Enter Name: " )
    time.sleep(1)
    print("")
    print("Hello " + Naam)
    time.sleep(1)
    print("")
    print("Ik vertel straks een verhaal over een meisje genaamd Parwana die gevlucht is uit haar land")
    time.sleep(1)
    print("")
    eerstevraag()

def vraag2():
    print("oke je wilt weten waar Parwana vandaan komt.")
    print("")
    time.sleep(3)
    print("Parwana was 8 jaar toen zij gevlucht was")
    print("")
    time.sleep(3)
    print("ze is gevlucht uit Afghanistan")
    print("")
    time.sleep(3)
    print("wat zou je nog meer willen weten")
    print("")
    time.sleep(3)
    print("A| Hoe is deze persoon is gevlucht?")
    time.sleep(3)
    print("")
    print("B| Waarom is deze persoon gevlucht")
    print("")
    time.sleep(3)
    print("Als je niks meer hoef te weten Type in: Nee|  ")
    print("")
    time.sleep(3)
    Answer = input("vul hier je keuze in.   |A/B/Nee: ")
    print("")
    time.sleep(3)
    if Answer == "A":
        print("Top laten we verder gaan!")
        time.sleep(3)
        vraag3()
    if Answer == "B":
        print("Top laten we verder gaan!")
        time.sleep(3)
        vraag4()
    if Answer == "Nee":
        time.sleep(2)
        print("")
        print("Bedankt voor het lezen van het verhaaltje")
        time.sleep(2)
        exit()

def vragen():               
    print("over wat wil je dat ik ga vertellen")
    print("")
    time.sleep(2)
    print("A|waar deze persoon vandaan komt")
    print("")
    time.sleep(2)
    print("B|Hoe deze versoon is gevlucht")
    time.sleep(2)
    print("")
    print("C|Waarom deze persoon is gevlucht?")
    time.sleep(2)
    print("")
    Answer = input("Vul hier in over wat je meer wilt weten. | A/B/C: ")
    time.sleep(3)
    if Answer == "A":
        print("Oke ik zal hier wat over vertellen!.")
        print("")
        time.sleep(3)
        vraag2()
    elif Answer == "B":
        print("Oke ik zal hier wat over vertellen!")
        print("")
        time.sleep(3)
        vraag3()
    elif Answer == "C":
        print("Oke ik zal hier wat over vertellen!")
        print("")
        time.sleep(3)
        vraag4()
    else:
        print("vul een geldig antwoord in")
        vragen()

def vraag3():
    print("")
    time.sleep(3)
    print("Dit verhaaltje gaat over hoe Parwana is gevlucht. ")
    time.sleep(3)
    print("")
    time.sleep(3)
    print("Toen 8 jaar was is ze gevlucht uit Afghanistan Parwana over land en water en met het paard.")
    print("")
    time.sleep(3)
    print("Tijdens de vlucht had ze heel weinig te eten")
    print("")
    time.sleep(3)
    print("ze vond het best vreemd dat ze laat in de nacht stiekem weg ging")
    print("")
    time.sleep(3)
    print("maar ze vond het ook wel spannend en leuk omdat ze niet echt besefte wat er echt aan de hand was")
    print("")
    time.sleep(3)
    print("Dit was hoe Parwana is gevlucht")
    print("")
    time.sleep(3)
    print("Wat zou je nogmeer willen weten")
    print("")
    time.sleep(3)
    print("A|Waarom deze persoon is gevlucht?")
    print("")
    time.sleep(3)
    print("B|Hoe is deze persoon is gevlucht?")
    print("")
    time.sleep(3)
    print("Nee: je wilt stoppen met dit verhaaltje")
    print("")
    time.sleep(3)
    Answer = input("Vul hier in over wat je meer wilt weten. | A/B/Nee: ")
    time.sleep(3)
    if Answer == "A":
        print("Oke ik zal hier wat over vertellen!.")
        time.sleep(3)
        print("")
        vraag2()
    elif Answer == "B":
        print("Oke ik zal hier wat over vertellen!")
        time.sleep(3)
        print("")
        vraag4()
    elif Answer == "Nee":
        print("")
        print("Bedankt voor het lezen van het verhaaltje")
        time.sleep(2)
        exit()
    else:
        print("vul een geldig antwoord in")
        time.sleep(1)
        vraag3()
    

def vraag4():
    time.sleep(1)
    print("Hier ga ik vertellen waàrom Parwana is gevlucht")
    print("")
    time.sleep(3)
    print("Parwana is gevlucht omdat haar vader een dreigbrief kreeg van de Taliban.")
    print("")
    time.sleep(3)
    print("Hij had die brief gekregen omdat haar vader voor internationale bedrijven werkten.")
    print("")
    time.sleep(3)
    print("Haar ooms waren al vermoord dus haar vader had geen keuze")
    print("")
    time.sleep(3)
    print("over welk ondedrwerp wil jij nog meer weten")
    print("")
    time.sleep(3)
    print("A|waar deze persoon vandaan komt")
    print("")
    time.sleep(3)
    print("B|Hoe deze versoon is gevlucht")
    print("")
    time.sleep(3)
    print("Nee: je wilt stoppen")
    Answer = input("")
    if Answer == "A":
        print("Oke ik zal hier wat over vertellen!.")
        time.sleep(3)
        vraag2()
    if Answer == "B":
        print("Oke ik zal hier wat over vertellen!.")
        vraag3()
    if Answer == "Nee":
        time.sleep(2)
        print("")
        print("Bedankt voor het lezen van het verhaaltje")
        time.sleep(2)
        exit()
    else:
        print("vul een geldig antwoord in !")
        vraag4()


start()